// Code generated by MockGen. DO NOT EDIT.
// Source: ./application/user/usecase.go

// Package mock_user is a generated GoMock package.
package mocks

import (
	models "github.com/go-park-mail-ru/2020_1_k-on/application/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// Add mocks base method
func (m *MockUseCase) Add(usr *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", usr)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add
func (mr *MockUseCaseMockRecorder) Add(usr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockUseCase)(nil).Add), usr)
}

// Get mocks base method
func (m *MockUseCase) Get(id uint) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockUseCaseMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUseCase)(nil).Get), id)
}

// Update mocks base method
func (m *MockUseCase) Update(user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockUseCaseMockRecorder) Update(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUseCase)(nil).Update), user)
}

// SetImage mocks base method
func (m *MockUseCase) SetImage(id uint, image string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetImage", id, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetImage indicates an expected call of SetImage
func (mr *MockUseCaseMockRecorder) SetImage(id, image interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetImage", reflect.TypeOf((*MockUseCase)(nil).SetImage), id, image)
}

// Oauth mocks base method
func (m *MockUseCase) Oauth(vkUser *models.VkUser) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Oauth", vkUser)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Oauth indicates an expected call of Oauth
func (mr *MockUseCaseMockRecorder) Oauth(vkUser interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Oauth", reflect.TypeOf((*MockUseCase)(nil).Oauth), vkUser)
}

// GetOauthConfig mocks base method
func (m *MockUseCase) GetOauthConfig() (*models.OauthConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOauthConfig")
	ret0, _ := ret[0].(*models.OauthConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOauthConfig indicates an expected call of GetOauthConfig
func (mr *MockUseCaseMockRecorder) GetOauthConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOauthConfig", reflect.TypeOf((*MockUseCase)(nil).GetOauthConfig))
}
