// Code generated by MockGen. DO NOT EDIT.
// Source: ./application/microservices/series/client/client.go

// Package mock_client is a generated GoMock package.
package client

import (
	models "github.com/go-park-mail-ru/2020_1_k-on/application/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockISeriesFilterClient is a mock of ISeriesFilterClient interface
type MockISeriesFilterClient struct {
	ctrl     *gomock.Controller
	recorder *MockISeriesFilterClientMockRecorder
}

// MockISeriesFilterClientMockRecorder is the mock recorder for MockISeriesFilterClient
type MockISeriesFilterClientMockRecorder struct {
	mock *MockISeriesFilterClient
}

// NewMockISeriesFilterClient creates a new mock instance
func NewMockISeriesFilterClient(ctrl *gomock.Controller) *MockISeriesFilterClient {
	mock := &MockISeriesFilterClient{ctrl: ctrl}
	mock.recorder = &MockISeriesFilterClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockISeriesFilterClient) EXPECT() *MockISeriesFilterClientMockRecorder {
	return m.recorder
}

// GetFilteredSeries mocks base method
func (m *MockISeriesFilterClient) GetFilteredSeries(fields map[string][]string) (models.SeriesArr, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilteredSeries", fields)
	ret0, _ := ret[0].(models.SeriesArr)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetFilteredSeries indicates an expected call of GetFilteredSeries
func (mr *MockISeriesFilterClientMockRecorder) GetFilteredSeries(fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilteredSeries", reflect.TypeOf((*MockISeriesFilterClient)(nil).GetFilteredSeries), fields)
}

// GetFilterFields mocks base method
func (m *MockISeriesFilterClient) GetFilterFields() (map[string]models.Genres, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilterFields")
	ret0, _ := ret[0].(map[string]models.Genres)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetFilterFields indicates an expected call of GetFilterFields
func (mr *MockISeriesFilterClientMockRecorder) GetFilterFields() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilterFields", reflect.TypeOf((*MockISeriesFilterClient)(nil).GetFilterFields))
}
