// Code generated by MockGen. DO NOT EDIT.
// Source: ./application/microservices/film/filter/repository.go

// Package mock_filter is a generated GoMock package.
package mocks

import (
	models "github.com/go-park-mail-ru/2020_1_k-on/application/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FilterFilmsList mocks base method
func (m *MockRepository) FilterFilmsList(arg0 map[string][]string) (*models.Films, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterFilmsList", arg0)
	ret0, _ := ret[0].(*models.Films)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// FilterFilmsList indicates an expected call of FilterFilmsList
func (mr *MockRepositoryMockRecorder) FilterFilmsList(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterFilmsList", reflect.TypeOf((*MockRepository)(nil).FilterFilmsList), arg0)
}

// FilterFilmData mocks base method
func (m *MockRepository) FilterFilmData() (map[string]models.Genres, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterFilmData")
	ret0, _ := ret[0].(map[string]models.Genres)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// FilterFilmData indicates an expected call of FilterFilmData
func (mr *MockRepositoryMockRecorder) FilterFilmData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterFilmData", reflect.TypeOf((*MockRepository)(nil).FilterFilmData))
}
