// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: sfilter.proto

package apis

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Strings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
}

func (x *Strings) Reset() {
	*x = Strings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sfilter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Strings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Strings) ProtoMessage() {}

func (x *Strings) ProtoReflect() protoreflect.Message {
	mi := &file_sfilter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Strings.ProtoReflect.Descriptor instead.
func (*Strings) Descriptor() ([]byte, []int) {
	return file_sfilter_proto_rawDescGZIP(), []int{0}
}

func (x *Strings) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields map[string]*Strings `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sfilter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_sfilter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_sfilter_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetFields() map[string]*Strings {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Series struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MainGenre       string  `protobuf:"bytes,2,opt,name=mainGenre,proto3" json:"mainGenre,omitempty"`
	RussianName     string  `protobuf:"bytes,3,opt,name=russianName,proto3" json:"russianName,omitempty"`
	EnglishName     string  `protobuf:"bytes,4,opt,name=englishName,proto3" json:"englishName,omitempty"`
	TrailerLink     string  `protobuf:"bytes,5,opt,name=trailerLink,proto3" json:"trailerLink,omitempty"`
	Rating          float64 `protobuf:"fixed64,6,opt,name=rating,proto3" json:"rating,omitempty"`
	ImdbRating      float64 `protobuf:"fixed64,7,opt,name=imdbRating,proto3" json:"imdbRating,omitempty"`
	TotalVotes      int64   `protobuf:"varint,8,opt,name=totalVotes,proto3" json:"totalVotes,omitempty"`
	SumVotes        int64   `protobuf:"varint,9,opt,name=sumVotes,proto3" json:"sumVotes,omitempty"`
	Description     string  `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Image           string  `protobuf:"bytes,11,opt,name=image,proto3" json:"image,omitempty"`
	BackgroundImage string  `protobuf:"bytes,12,opt,name=backgroundImage,proto3" json:"backgroundImage,omitempty"`
	Country         string  `protobuf:"bytes,13,opt,name=country,proto3" json:"country,omitempty"`
	YearFirst       int64   `protobuf:"varint,14,opt,name=yearFirst,proto3" json:"yearFirst,omitempty"`
	YearLast        int64   `protobuf:"varint,15,opt,name=yearLast,proto3" json:"yearLast,omitempty"`
	AgeLimit        int64   `protobuf:"varint,16,opt,name=ageLimit,proto3" json:"ageLimit,omitempty"`
}

func (x *Series) Reset() {
	*x = Series{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sfilter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Series) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Series) ProtoMessage() {}

func (x *Series) ProtoReflect() protoreflect.Message {
	mi := &file_sfilter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Series.ProtoReflect.Descriptor instead.
func (*Series) Descriptor() ([]byte, []int) {
	return file_sfilter_proto_rawDescGZIP(), []int{2}
}

func (x *Series) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Series) GetMainGenre() string {
	if x != nil {
		return x.MainGenre
	}
	return ""
}

func (x *Series) GetRussianName() string {
	if x != nil {
		return x.RussianName
	}
	return ""
}

func (x *Series) GetEnglishName() string {
	if x != nil {
		return x.EnglishName
	}
	return ""
}

func (x *Series) GetTrailerLink() string {
	if x != nil {
		return x.TrailerLink
	}
	return ""
}

func (x *Series) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Series) GetImdbRating() float64 {
	if x != nil {
		return x.ImdbRating
	}
	return 0
}

func (x *Series) GetTotalVotes() int64 {
	if x != nil {
		return x.TotalVotes
	}
	return 0
}

func (x *Series) GetSumVotes() int64 {
	if x != nil {
		return x.SumVotes
	}
	return 0
}

func (x *Series) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Series) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Series) GetBackgroundImage() string {
	if x != nil {
		return x.BackgroundImage
	}
	return ""
}

func (x *Series) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Series) GetYearFirst() int64 {
	if x != nil {
		return x.YearFirst
	}
	return 0
}

func (x *Series) GetYearLast() int64 {
	if x != nil {
		return x.YearLast
	}
	return 0
}

func (x *Series) GetAgeLimit() int64 {
	if x != nil {
		return x.AgeLimit
	}
	return 0
}

type SeriesList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Series `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *SeriesList) Reset() {
	*x = SeriesList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sfilter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeriesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesList) ProtoMessage() {}

func (x *SeriesList) ProtoReflect() protoreflect.Message {
	mi := &file_sfilter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesList.ProtoReflect.Descriptor instead.
func (*SeriesList) Descriptor() ([]byte, []int) {
	return file_sfilter_proto_rawDescGZIP(), []int{3}
}

func (x *SeriesList) GetList() []*Series {
	if x != nil {
		return x.List
	}
	return nil
}

type Genre struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Reference string `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
}

func (x *Genre) Reset() {
	*x = Genre{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sfilter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Genre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genre) ProtoMessage() {}

func (x *Genre) ProtoReflect() protoreflect.Message {
	mi := &file_sfilter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genre.ProtoReflect.Descriptor instead.
func (*Genre) Descriptor() ([]byte, []int) {
	return file_sfilter_proto_rawDescGZIP(), []int{4}
}

func (x *Genre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Genre) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

type Genres struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Genre `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *Genres) Reset() {
	*x = Genres{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sfilter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Genres) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genres) ProtoMessage() {}

func (x *Genres) ProtoReflect() protoreflect.Message {
	mi := &file_sfilter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genres.ProtoReflect.Descriptor instead.
func (*Genres) Descriptor() ([]byte, []int) {
	return file_sfilter_proto_rawDescGZIP(), []int{5}
}

func (x *Genres) GetList() []*Genre {
	if x != nil {
		return x.List
	}
	return nil
}

type FilterFields struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields map[string]*Genres `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *FilterFields) Reset() {
	*x = FilterFields{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sfilter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterFields) ProtoMessage() {}

func (x *FilterFields) ProtoReflect() protoreflect.Message {
	mi := &file_sfilter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterFields.ProtoReflect.Descriptor instead.
func (*FilterFields) Descriptor() ([]byte, []int) {
	return file_sfilter_proto_rawDescGZIP(), []int{6}
}

func (x *FilterFields) GetFields() map[string]*Genres {
	if x != nil {
		return x.Fields
	}
	return nil
}

type EmptyArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyArgs) Reset() {
	*x = EmptyArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sfilter_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyArgs) ProtoMessage() {}

func (x *EmptyArgs) ProtoReflect() protoreflect.Message {
	mi := &file_sfilter_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyArgs.ProtoReflect.Descriptor instead.
func (*EmptyArgs) Descriptor() ([]byte, []int) {
	return file_sfilter_proto_rawDescGZIP(), []int{7}
}

var File_sfilter_proto protoreflect.FileDescriptor

var file_sfilter_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x61, 0x70, 0x69, 0x73, 0x22, 0x1f, 0x0a, 0x07, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x30, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x1a, 0x48, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xe2, 0x03,
	0x0a, 0x06, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x69, 0x6e,
	0x47, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x69,
	0x6e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x75, 0x73, 0x73, 0x69, 0x61,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x75, 0x73,
	0x73, 0x69, 0x61, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x67, 0x6c,
	0x69, 0x73, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65,
	0x6e, 0x67, 0x6c, 0x69, 0x73, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72,
	0x61, 0x69, 0x6c, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x74, 0x72, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6d, 0x64, 0x62, 0x52, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x69, 0x6d, 0x64, 0x62, 0x52, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x56, 0x6f, 0x74,
	0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x56,
	0x6f, 0x74, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x75, 0x6d, 0x56, 0x6f, 0x74, 0x65, 0x73,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x75, 0x6d, 0x56, 0x6f, 0x74, 0x65, 0x73,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x62, 0x61, 0x63, 0x6b,
	0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x79, 0x65, 0x61, 0x72, 0x46, 0x69, 0x72, 0x73, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x79, 0x65, 0x61, 0x72, 0x46, 0x69, 0x72, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x79, 0x65,
	0x61, 0x72, 0x4c, 0x61, 0x73, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x79, 0x65,
	0x61, 0x72, 0x4c, 0x61, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x22, 0x2e, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x20, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x22, 0x39, 0x0a, 0x05, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x29, 0x0a,
	0x06, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x47, 0x65, 0x6e,
	0x72, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x8f, 0x01, 0x0a, 0x0c, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x36, 0x0a, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x73,
	0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x1a, 0x47, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x0b, 0x0a, 0x09, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x41, 0x72, 0x67, 0x73, 0x32, 0x7f, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x69, 0x65,
	0x73, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69,
	0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x12, 0x2e, 0x61, 0x70,
	0x69, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22,
	0x00, 0x12, 0x35, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x65, 0x64,
	0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x1a, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x69,
	0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sfilter_proto_rawDescOnce sync.Once
	file_sfilter_proto_rawDescData = file_sfilter_proto_rawDesc
)

func file_sfilter_proto_rawDescGZIP() []byte {
	file_sfilter_proto_rawDescOnce.Do(func() {
		file_sfilter_proto_rawDescData = protoimpl.X.CompressGZIP(file_sfilter_proto_rawDescData)
	})
	return file_sfilter_proto_rawDescData
}

var file_sfilter_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_sfilter_proto_goTypes = []interface{}{
	(*Strings)(nil),      // 0: apis.Strings
	(*Filter)(nil),       // 1: apis.Filter
	(*Series)(nil),       // 2: apis.Series
	(*SeriesList)(nil),   // 3: apis.SeriesList
	(*Genre)(nil),        // 4: apis.Genre
	(*Genres)(nil),       // 5: apis.Genres
	(*FilterFields)(nil), // 6: apis.FilterFields
	(*EmptyArgs)(nil),    // 7: apis.EmptyArgs
	nil,                  // 8: apis.Filter.FieldsEntry
	nil,                  // 9: apis.FilterFields.FieldsEntry
}
var file_sfilter_proto_depIdxs = []int32{
	8, // 0: apis.Filter.fields:type_name -> apis.Filter.FieldsEntry
	2, // 1: apis.SeriesList.list:type_name -> apis.Series
	4, // 2: apis.Genres.list:type_name -> apis.Genre
	9, // 3: apis.FilterFields.fields:type_name -> apis.FilterFields.FieldsEntry
	0, // 4: apis.Filter.FieldsEntry.value:type_name -> apis.Strings
	5, // 5: apis.FilterFields.FieldsEntry.value:type_name -> apis.Genres
	7, // 6: apis.SeriesFilter.GetFilterFields:input_type -> apis.EmptyArgs
	1, // 7: apis.SeriesFilter.GetFilteredSeries:input_type -> apis.Filter
	6, // 8: apis.SeriesFilter.GetFilterFields:output_type -> apis.FilterFields
	3, // 9: apis.SeriesFilter.GetFilteredSeries:output_type -> apis.SeriesList
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_sfilter_proto_init() }
func file_sfilter_proto_init() {
	if File_sfilter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sfilter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Strings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sfilter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sfilter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Series); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sfilter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeriesList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sfilter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Genre); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sfilter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Genres); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sfilter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterFields); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sfilter_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sfilter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sfilter_proto_goTypes,
		DependencyIndexes: file_sfilter_proto_depIdxs,
		MessageInfos:      file_sfilter_proto_msgTypes,
	}.Build()
	File_sfilter_proto = out.File
	file_sfilter_proto_rawDesc = nil
	file_sfilter_proto_goTypes = nil
	file_sfilter_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SeriesFilterClient is the client API for SeriesFilter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SeriesFilterClient interface {
	GetFilterFields(ctx context.Context, in *EmptyArgs, opts ...grpc.CallOption) (*FilterFields, error)
	GetFilteredSeries(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*SeriesList, error)
}

type seriesFilterClient struct {
	cc grpc.ClientConnInterface
}

func NewSeriesFilterClient(cc grpc.ClientConnInterface) SeriesFilterClient {
	return &seriesFilterClient{cc}
}

func (c *seriesFilterClient) GetFilterFields(ctx context.Context, in *EmptyArgs, opts ...grpc.CallOption) (*FilterFields, error) {
	out := new(FilterFields)
	err := c.cc.Invoke(ctx, "/apis.SeriesFilter/GetFilterFields", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seriesFilterClient) GetFilteredSeries(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*SeriesList, error) {
	out := new(SeriesList)
	err := c.cc.Invoke(ctx, "/apis.SeriesFilter/GetFilteredSeries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeriesFilterServer is the server API for SeriesFilter service.
type SeriesFilterServer interface {
	GetFilterFields(context.Context, *EmptyArgs) (*FilterFields, error)
	GetFilteredSeries(context.Context, *Filter) (*SeriesList, error)
}

// UnimplementedSeriesFilterServer can be embedded to have forward compatible implementations.
type UnimplementedSeriesFilterServer struct {
}

func (*UnimplementedSeriesFilterServer) GetFilterFields(context.Context, *EmptyArgs) (*FilterFields, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFilterFields not implemented")
}
func (*UnimplementedSeriesFilterServer) GetFilteredSeries(context.Context, *Filter) (*SeriesList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFilteredSeries not implemented")
}

func RegisterSeriesFilterServer(s *grpc.Server, srv SeriesFilterServer) {
	s.RegisterService(&_SeriesFilter_serviceDesc, srv)
}

func _SeriesFilter_GetFilterFields_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeriesFilterServer).GetFilterFields(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.SeriesFilter/GetFilterFields",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeriesFilterServer).GetFilterFields(ctx, req.(*EmptyArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeriesFilter_GetFilteredSeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeriesFilterServer).GetFilteredSeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.SeriesFilter/GetFilteredSeries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeriesFilterServer).GetFilteredSeries(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

var _SeriesFilter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apis.SeriesFilter",
	HandlerType: (*SeriesFilterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFilterFields",
			Handler:    _SeriesFilter_GetFilterFields_Handler,
		},
		{
			MethodName: "GetFilteredSeries",
			Handler:    _SeriesFilter_GetFilteredSeries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sfilter.proto",
}
