name: Build service

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: sudo sh scripts/start.sh

      - name: Check dir
        run: ls build/ -la

      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build file
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Transfer build file to server
        uses: appleboy/scp-action@v0.0.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "build/*"
          target: "/./backend/src/github.com/go-park-mail-ru/2020_1_k-on/"
      - name: chmod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: chmod 755 -R /./backend/src/github.com/go-park-mail-ru/2020_1_k-on/build
      - name: restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /./backend/src/github.com/go-park-mail-ru/2020_1_k-on/build
            ls -la
            ./go_series_service &
            ./go_film_service &
            ./go_auth_service &
            ./go_main_service &